# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GDP App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GDP App
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'ObjectMapper'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

  target 'GDP AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GDP AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
